### ISSUE TITLE
Some minor issues

### ISSUE THREAD

**Issue by schungx** [rhaiscript/rhai-fs#1]
* for blobs there is `max_array_size` similar to strings
* Is it a good idea to read the file and then truncate to max? The file might be deliberately made huge si you crash the engine. Maybe use a read call with length is better ...
* necessary to introduce the `PathBuf` type? Or just use string paths... With helpers to manipulate segments
* `max_string_len` etc. may be zero to indicate unlimited; you'd need to use `>=0`
* The limits are probably not available under `unchecked` so you may need an additional feature gate... Or maybe I'll make the get calls available all the time but return zero under `unchecked` EDIT: I've made the `max_...` calls available even under `unchecked` so you don't have to include yet another feature flag.

**Comment by emesare** [comment]
Thanks for the overview, I'll have these fixed soon. 

For why we use PathBuf it is so that there is a single api to control file and dir. I can add a helper that will take a string and just call the path function through the engine, this way integrators only need to override the path function when they want to restrict access.

**Comment by schungx** [comment]
Makes sense!

**Comment by emesare** [comment]
All the agreed upon changes have been merged, thank you for reporting!
